//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghe_ngoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ghe_ngoi()
        {
            this.order_details = new HashSet<order_details>();
            this.ve_ban = new HashSet<ve_ban>();
        }
    
        public int id { get; set; }
        public Nullable<bool> da_chon { get; set; }
        public Nullable<int> phong_chieu_id { get; set; }
        public Nullable<int> loai_ghe_id { get; set; }
        public Nullable<decimal> gia { get; set; }
        public string image { get; set; }
        public string Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual phong_chieu phong_chieu { get; set; }
        public virtual loai_ghe loai_ghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ve_ban> ve_ban { get; set; }
    }
}
