//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lien_he
    {
        public int id { get; set; }
        public string ho_ten { get; set; }
        public string email { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung { get; set; }
        public string tra_loi { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<int> status { get; set; }
    }
}
