//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_phim_theloai
    {
        public int ID { get; set; }
        public Nullable<int> id_phim { get; set; }
        public Nullable<int> id_theloai { get; set; }
    
        public virtual the_loai_phim the_loai_phim { get; set; }
        public virtual phim phim { get; set; }
    }
}
