//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_phim_dienvien
    {
        public long ID { get; set; }
        public int id_phim { get; set; }
        public int id_dienvien { get; set; }
    
        public virtual dien_vien dien_vien { get; set; }
        public virtual phim phim { get; set; }
    }
}
