//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_khachhang { get; set; }
        public string ten_khach_hang { get; set; }
        public string ten_phim { get; set; }
        public Nullable<int> id_phim { get; set; }
        public Nullable<int> so_luong_ve { get; set; }
        public string code_ticket { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public string the_loai_phim { get; set; }
        public Nullable<int> id_phong_chieu { get; set; }
        public string ten_phong_chieu { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> ngay_mua { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual phong_chieu phong_chieu { get; set; }
        public virtual phim phim { get; set; }
    }
}
