//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public string ten_ghe { get; set; }
        public Nullable<int> id_orders { get; set; }
        public Nullable<int> id_ghe { get; set; }
        public Nullable<decimal> gia_ve { get; set; }
        public Nullable<decimal> gia_ghe_ngoi { get; set; }
    
        public virtual ghe_ngoi ghe_ngoi { get; set; }
        public virtual order order { get; set; }
    }
}
