//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phim()
        {
            this.list_phim_dienvien = new HashSet<list_phim_dienvien>();
            this.list_phim_theloai = new HashSet<list_phim_theloai>();
            this.suat_chieu = new HashSet<suat_chieu>();
            this.orders = new HashSet<order>();
            this.phim_daodien = new HashSet<phim_daodien>();
        }
    
        public int id { get; set; }
        public string ten_phim { get; set; }
        public Nullable<decimal> gia { get; set; }
        public string chi_tiet { get; set; }
        public string trailer { get; set; }
        public string slug { get; set; }
        public string anh { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> thoi_luong { get; set; }
        public Nullable<System.DateTime> ngay_cong_chieu { get; set; }
        public Nullable<int> loai_phim_chieu { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<int> dao_dien_id { get; set; }
        public Nullable<int> dien_vien_id { get; set; }
        public Nullable<int> the_loai_phim_id { get; set; }
        public string anhbackground { get; set; }
        public string idrating { get; set; }
        public Nullable<int> id_content_rating { get; set; }
    
        public virtual content_rating content_rating { get; set; }
        public virtual dao_dien dao_dien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_phim_dienvien> list_phim_dienvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_phim_theloai> list_phim_theloai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suat_chieu> suat_chieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phim_daodien> phim_daodien { get; set; }
        public virtual the_loai_phim the_loai_phim { get; set; }
    }
}
