//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suatchieu_timeframe
    {
        public int id { get; set; }
        public Nullable<int> id_Suatchieu { get; set; }
        public Nullable<int> id_Timeframe { get; set; }
    
        public virtual suat_chieu suat_chieu { get; set; }
        public virtual TimeFrame TimeFrame { get; set; }
    }
}
