//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thong_tin_cong_ty
    {
        public int id { get; set; }
        public string ten_rap { get; set; }
        public string dia_chi { get; set; }
        public Nullable<int> phong_chieu { get; set; }
        public Nullable<int> status { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    }
}
