//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_ban
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngay_ban { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public Nullable<int> suat_chieu_id { get; set; }
        public Nullable<int> gia_ve_id { get; set; }
        public Nullable<int> ghe_id { get; set; }
        public Nullable<int> users_id { get; set; }
    
        public virtual ghe_ngoi ghe_ngoi { get; set; }
        public virtual gia_ve gia_ve { get; set; }
        public virtual suat_chieu suat_chieu { get; set; }
        public virtual user user { get; set; }
    }
}
